### ISSUE TITLE
Speaker cards

### ISSUE THREAD

**Issue by derberg** [asyncapi/conference-website#104]
As identified on last conference-org meeting -> https://github.com/orgs/asyncapi/discussions/381 we need speaker cards

Examples of speaker cards from 2021 conf:

![SpeakerCard_Conference_16-1_Aayush](https://user-images.githubusercontent.com/6995927/192275683-78c77425-b46d-49cd-a5c8-7a7bfaff2bfe.jpg)
![SpeakerCard_Conference_17-3_Ludovic_Antoine](https://user-images.githubusercontent.com/6995927/192275701-6f007579-56c0-4180-af16-bb2c6498325d.jpg)

We need similar but just with current conference branding

Some key facts:
- sometimes there is one and sometimes 2 speakers
- all talks are listed in https://asyncapi2022.sched.com/
- all speakers are listed in https://asyncapi2022.sched.com/ when you click on `Speakers` link. Some speakers provided profile picture.
- as you can see, speaker card without a speaker profile picture is not the nicest. @derberg contacted all speakers to provide their profile picture

cc @Mayaleeeee @mcturco

**Comment by derberg** [comment]
Profile picture from Pratik 

![IMG_20220926_174844](https://user-images.githubusercontent.com/6995927/192276555-50cb50ea-90ca-47f4-be7f-ae3fa9531680.jpg)

**Comment by derberg** [comment]
Alejandra

![Image from iOS](https://user-images.githubusercontent.com/6995927/192285947-ec41a6c9-1d56-41c4-86cf-736e2b30009d.jpg)

Jesse

![jesse-menning-headshot-on-ping](https://user-images.githubusercontent.com/6995927/192286083-6fdea3da-78d0-4063-876a-623edcc0587e.png)

Ismael 

![2021-09-22](https://user-images.githubusercontent.com/6995927/192286176-d3f5f398-964b-4af8-a144-6be9d794c423.jpg)

Pablo Jose Lopez Rivadulla

![FotoPerfil](https://user-images.githubusercontent.com/6995927/192286425-7f905563-b793-4a1e-94cf-6710e7a91da3.jpg)

**Comment by derberg** [comment]
Nelson

![IMG_1804](https://user-images.githubusercontent.com/6995927/192288158-5a4070a8-c286-48fe-b9d7-e09c9fb033f7.jpg)

**Comment by Mayaleeeee** [comment]
Niceeee🥰🥰

I'll start working on it @derberg

**Comment by mcturco** [comment]
@Mayaleeeee here is a link to the figma file for last year's speaker cards: https://www.figma.com/file/HN7QrFterf4JZ7AyTRZ2y1/Speaker-Cards?node-id=2%3A26

I think that size worked best, so if you want to use the same layout and just change the visual design to match the art direction of this year's conference, that would be awesome!

Conference 2022 Art Direction Figma: https://www.figma.com/file/ldUyQL53HBoQjEqaC1QGRr/Conference-2022-Website?node-id=12%3A379

**Comment by Mayaleeeee** [comment]
@mcturco Thank you🥰

This is really gonna speed up my work. Also the conference art design is really beautiful😍😍😍.

Could you also show me the one from the previous year??

**Comment by derberg** [comment]
@Mayaleeeee 2021 and 2020 was very simplistic, and it was just based on some generic template as we did not have Missy yet 😄 

- https://conference.2021.asyncapi.com/
- https://conference.2020.asyncapi.com/

**Comment by derberg** [comment]
More profile pictures:

Rob and Natalie
![rob-galanakis-lithic-profile](https://user-images.githubusercontent.com/6995927/192446440-49beb5fe-acf6-4699-913d-c2fb5575b0f6.jpg)
![natalie-edson-lithic-profile](https://user-images.githubusercontent.com/6995927/192446445-361ceae2-780a-4e07-a3eb-65928949b7a6.jpg)

James

![James_Sept_2022](https://user-images.githubusercontent.com/6995927/192446535-69a7d69c-f147-4cda-a9d4-b389e791fd49.jpg)


Dan


![dan-farrelly-headshot-400](https://user-images.githubusercontent.com/6995927/192446642-7d769eeb-390e-40fe-9836-9fd92158f272.jpeg)

Tamimi

![vwW0UZBG](https://user-images.githubusercontent.com/6995927/192447243-48604713-9662-432b-8b09-f630d579cc92.jpg)

Florence


![DSC_1365](https://user-images.githubusercontent.com/6995927/192449578-e049d8fd-0867-47cb-b5b9-75918e8b68df.jpg)

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee 2021 and 2020 was very simplistic, and it was just based on some generic template as we did not have Missy yet 😄 
> 
> - https://conference.2021.asyncapi.com/
> - https://conference.2020.asyncapi.com/

That's cool then🥰🥰
Thank you.

**Comment by Mayaleeeee** [comment]
[](https://www.figma.com/file/GDWsSRxb19acJuTefvIBPW/Speaker-Cards-2022?node-id=0%3A1)

**Comment by Mayaleeeee** [comment]
@mcturco @derberg 
Here's an update on the speaker cards. If there is anything I omitted or you believe I've done incorrectly, please let me know.

I'm open to feedbacks.


![Screenshots_2022-09-28-00-01-49.png](https://user-images.githubusercontent.com/105395613/192654003-08645682-69ce-47ce-ba66-bd6072b36e27.png)

![Screenshots_2022-09-28-00-02-22.png](https://user-images.githubusercontent.com/105395613/192654038-effdf1c2-81da-40ee-ab21-b6b064dccf5f.png)

![Screenshots_2022-09-28-00-02-41.png](https://user-images.githubusercontent.com/105395613/192654051-8d9e0e91-f1f0-4ea4-81ff-22b7f189592b.png)

![Screenshots_2022-09-28-00-03-04.png](https://user-images.githubusercontent.com/105395613/192654064-105b0fa6-8663-4228-9eb4-cdc3db29ceae.png)

![Screenshots_2022-09-28-00-03-27.png](https://user-images.githubusercontent.com/105395613/192654075-3751ed8d-9f98-4d98-a4ac-825159cb56c1.png)

![Screenshots_2022-09-28-00-03-56.png](https://user-images.githubusercontent.com/105395613/192654083-4b737458-882b-4e76-87b0-ba6c990948bd.png)

**Comment by Mayaleeeee** [comment]
@derberg I'm not sure, but was this planned to occur at the same time? I'm a little perplexed because I discovered the themes were different when I tried to create a single card for two speakers who will present at the same time.
[https://asyncapi2022.sched.com/](url)

![Same time](https://user-images.githubusercontent.com/105395613/192656560-cec5eaf0-ecdd-4c65-a259-f058b9f56ec8.jpg)

**Comment by fmvilas** [comment]
Love it. Especially the first and second ones.

The items in the bottom banner seem to be misaligned. For instance, "Virtual Conference" seems to be aligned with "conference.asyncapi.com" but not with "Conf 2022". I think you vertically aligned all the items but, due to the bigger size of "Conf 2022", it's perceived as having more weight than the rest of the items.

Suggestions:
1. Maybe you can align "Virtual Conference" with "Conf 2022". Not sure it would work though as you'll have the same issue with "conference.asyncapi.com".
2. Grouping "Virtual Conference" and "conference.asyncapi.com" together on the right side (one above another). This way you may balance the weight on both sides.
3. You move "Virtual Conference" to the top (near the date and time). Something like `November 03, 2022 | 12:00 UTC | Virtual`.

Hope that helps :)

**Comment by derberg** [comment]
@Mayaleeeee, thanks for the info. I already asked LF to fix that, there should be only Jonas.

regarding speaker cards, I let others share opinion 😄 I can only write that I love dark theme 😄

**Comment by Mayaleeeee** [comment]
@derberg I thought as much too.

Thank you🥰

**Comment by fmvilas** [comment]
Still not aligned but getting closer. In general, texts should be aligned by their baseline. Right now, "Conf 2022" and "Virtual Conference" are aligned by their top line (or almost), and "Virtual Conference" and the link are aligned by their baseline/underline.

![Captura de Pantalla 2022-09-28 a las 17 58 54](https://user-images.githubusercontent.com/242119/192828227-f8c1495f-1617-4860-b493-d677a6282077.png)

I think if you aligned everything by their baseline, it may look good and balanced but not quite sure 😄

**Comment by Mayaleeeee** [comment]
Here we go @fmvilas 🙈🙈🙈
Lemme know if there's any other thing that needs to be corrected.

Thank you.

![Screenshots_2022-09-29-00-31-49.png](https://user-images.githubusercontent.com/105395613/192906390-8901f9ec-bf90-4a0d-b9dd-969cb76e45c9.png)




![Screenshots_2022-09-29-00-31-26.png](https://user-images.githubusercontent.com/105395613/192906366-0c669567-a1e1-4e17-b587-f5d70a9a158e.png)

**Comment by fmvilas** [comment]
Nice! I think it looks great now 👏

**Comment by alequetzalli** [comment]
So instead of "Conf 2022 Virtual Conference"... how about, "**2022 AsyncAPI Conference** _Online_"?

**Comment by Mayaleeeee** [comment]
I apologize for the delayed response, @alequetzalli 
Okay, I think that it can be changed, however I've been considering how to write it such that the cards would still display the AsyncAPI logo. 
Because if I'm to write it as "2022 AsyncAPI Online Conference," the logo would appear in between the year and the name.

Check these out
![Screenshots_2022-10-03-15-17-01](https://user-images.githubusercontent.com/105395613/193600596-e2a29bda-d25a-4881-8bef-6458cd1a7e59.png)
![Screenshots_2022-10-03-15-16-21](https://user-images.githubusercontent.com/105395613/193601089-72166d00-c443-4a23-b25d-8e048d055ea1.png)
g)
![Screenshots_2022-10-03-15-16-46 (1)](https://user-images.githubusercontent.com/105395613/193601365-4b2b02ea-11ce-44d2-8da9-23368c60eae5.png)


Which one do you think is preferable?

**Comment by alequetzalli** [comment]
@Mayaleeeee hmmm I would vote for ...

https://user-images.githubusercontent.com/105395613/193601089-72166d00-c443-4a23-b25d-8e048d055ea1.png

**Comment by alequetzalli** [comment]
Also thinking again, prob better to write "2022 AsyncAPI Online Conference" 😄

**Comment by Mayaleeeee** [comment]
Niceeee @alequetzalli

**Comment by derberg** [comment]
@Mayaleeeee looks like we have it, right? I also uploaded all the photos of speakers to this issue. So I guess you can proceed with creating cards

unless we are still missing something?

**Comment by Mayaleeeee** [comment]
Yeah, everything is ready @derberg 
I should be done with it before the end of today/tomorrow morning.

**Comment by derberg** [comment]
Closing, all ready. Thanks @Mayaleeeee 🙇🏼

**Comment by Mayaleeeee** [comment]
I'm glad I was able to contribute🥰🥰
