### ISSUE TITLE
Paris Conference Official Announcement Design

### ISSUE THREAD

**Issue by iambami** [asyncapi/conference-website#451]
Paris Conference Official Announcement Design: "AsyncAPI is Coming to Paris." Thanks to our Venue Sponsor at APIDays."

Add APIDays logo to it. https://www.apidays.global/

### AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

### AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design

**Comment by miracle-E** [comment]
Working on it @iambami

**Comment by iambami** [comment]
Thanks @miracle-E

**Comment by miracle-E** [comment]
Check the design @iambami ![Image](https://github.com/user-attachments/assets/f2f3f7cb-be9d-4165-9e93-0c0f860b1986)

**Comment by iambami** [comment]
I think it's too busy, maybe it's me

@Mayaleeeee @thulieblack wdyt?

**Comment by Mayaleeeee** [comment]
> I think it's too busy, maybe it's me
> 
> @Mayaleeeee @thulieblack wdyt?
> 

Thank you @miracle-E 

I feel the same, too @iambami 


@miracle-E 
I suggest you decrease the size of the whole text. They are all trying to get attention at the same time, and that's why it looks busy.


Here are a few inspirations you can check out.

![111cf19beaabdcbaa17f0cd7dc98054f.jpg](https://github.com/user-attachments/assets/b224eef8-b7a0-4e07-a728-76583a5432d4)

![6076bf9717419c516d7f60a92e923ca9.jpg](https://github.com/user-attachments/assets/4ed975b3-44a1-401d-911e-b48f1fe43523)

![3e75c3ec718dd4c17f103bf8e5d33261.jpg](https://github.com/user-attachments/assets/7a6291f5-13be-4e6c-823d-36ae428f321b)

![2f2a68e3b2065352e18d1547a7370ae9.jpg](https://github.com/user-attachments/assets/4295d82d-fd96-4e27-9b6c-59afa2a5c0f6)

**Comment by thulieblack** [comment]
Find me weird but I like the design 🙈 but I suggest reducing the font size and it should be AsyncAPI Conf in Paris/ AsyncAPI Conference is Coming to Paris.

To justify why I like it, it touches both branding colours from the sponsor and AsyncAPI. But the font is too big.

In corporate some of Maya's suggestions to improve the current one

**Comment by iambami** [comment]
I was talking about the font as well

**Comment by miracle-E** [comment]
Alright. Thank you for the feedback
![Image](https://github.com/user-attachments/assets/cabf7ebc-e346-43ef-8d53-5f92f2b4b082)
![Image](https://github.com/user-attachments/assets/05b1e053-03fa-4289-8031-be12e9fc5603)

**Comment by miracle-E** [comment]
![Image](https://github.com/user-attachments/assets/cbf2cc4a-77eb-4d87-87cd-874298cc569a)
@iambami

**Comment by iambami** [comment]
Thanks @miracle-E
